# General
base_url = "https://example.com"
compile_sass = false
minify_html = true
generate_feeds = true
generate_sitemap = true

# Taxonomies
taxonomies = [
    {name = "tags", feed = true, paginate_by = 10},
]

# Language
default_language = "jp"

[languages.en]
build_search_index = true
title = "kauai tech-blog"
description = "Just another embedded engineer's development blog"

[languages.jp]
build_search_index = true
title = "kauai tech-blog"
description = "しがない組み込みエンジニアの開発ブログ"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
extra_syntaxes_and_themes = ["static/syntax_themes"]
highlight_theme = "Dimmed_Monokai"
highlight_lines = "all"
highlight_linenos = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

# Extra
[extra]
author = "5q2bc"
favicon = "logo.png"
list_pages = false
twitter_card = true
enable_search = true

## Navigation
header_nav = [
  { url = "/", name_en = "/home/", name_jp = "/accueil/" },
  { url = "/about", name_en = "/about/", name_jp = "/concernant/" },
  { url = "/blog", name_en = "/blog/", name_jp = "/blog/" }
]
